apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-ui
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.serviceui.name | default "ui" }}
    infoEndpoint: "/ui/info"
    healthEndpoint: "/ui/health"
    {{- with .Values.serviceui.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.serviceui.service.type | default "ClusterIP"}}
  ports:
  - name: {{ $.Values.serviceui.service.portName | default "headless" }}
    port: 8080
    protocol: TCP
    targetPort: 8080
{{- if and (or (eq .Values.serviceui.service.type "NodePort") (eq .Values.serviceui.service.type "LoadBalancer")) (not (empty .Values.serviceui.service.nodePort)) }}
    nodePort: {{ .Values.serviceui.service.nodePort }}
{{- end }}
{{- if .Values.serviceui.service.extraPorts }}
  {{ toYaml .Values.serviceui.service.extraPorts | indent 2 }}
{{- end }}
  selector:
    component: {{ include "reportportal.fullname" . }}-ui