{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "reportportal.fullname" . }}-service-manager
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "3"
rules:
  {{- if .Values.rbac.rules }}
    {{- toYaml .Values.rbac.rules | nindent 4 }}
  {{- else }}
  # Allow the service account to get and list pods, services, and jobs
  - apiGroups: ["", "batch"]
    resources: ["pods","services", "jobs"]
    verbs: ["get", "list", "watch"]
  # Allow the service account to delete jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["delete"]
  {{- end}}
{{- end }}