{{- if and .Values.rbac.create .Values.global.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reportportal.fullname" . }}-user-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.argocd.enabled }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "4"
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "reportportal.fullname" . }}-service-manager
subjects:
  - kind: ServiceAccount
    name: {{ template "reportportal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}