{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "reportportal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
    annotations:
      {{- if .Values.global.argocd.enabled }}
      "helm.sh/hook": pre-upgrade
      "helm.sh/hook-weight": "5"
      {{- end }}
      {{- if .Values.global.serviceAccount.annotations }}
      {{- range $key, $value := .Values.global.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
{{- end }}