apiVersion: v1
appVersion: "5.3.4"
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 5.3.4
sources:
  - https://github.com/reportportal/k8s/reportportal
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io
engine: gotpl
