version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: helm
    directory: /reportportal
    target-branch: develop
    exclude-paths:
      - reportportal/values.yaml
      - "*/values.yaml"
    schedule:
      interval: weekly
    groups:
      helm-dependencies:
        patterns:
          - "*"
