apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "reportportal.fullname" . }}-analyzer-train
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-analyzer-train
  serviceName: {{ include "reportportal.fullname" . }}-analyzertrain
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.serviceanalyzertrain.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-analyzer-train
      annotations:
        {{- range $key, $value := .Values.serviceanalyzertrain.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: migrations-waiting-init
        image: "{{ .Values.k8sWaitFor.image.repository }}:{{ .Values.k8sWaitFor.image.tag }}"
        imagePullPolicy: IfNotPresent
        args:
          - "pod-wr"
          - "-lcomponent={{ include "reportportal.fullname" . }}-api"
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
{{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
{{- end }}
      containers:
      - name: "{{ $.Values.serviceanalyzertrain.name | default "analyzer-train" }}"
        image: "{{ .Values.serviceanalyzer.image.repository }}:{{ .Values.serviceanalyzer.image.tag }}"
        imagePullPolicy: "{{ .Values.serviceanalyzertrain.pullPolicy }}"
        ports:
        - containerPort: 5001
          name: analyzertrain
        resources:
          requests:
            cpu: {{ .Values.serviceanalyzertrain.resources.requests.cpu }}
            memory: {{ .Values.serviceanalyzertrain.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceanalyzertrain.resources.limits.cpu }}
            memory: {{ .Values.serviceanalyzertrain.resources.limits.memory }}
        env:
{{- if .Values.serviceanalyzertrain.extraEnvs }}
{{ toYaml .Values.serviceanalyzertrain.extraEnvs | indent 8 }}
{{- end }}
        {{- if eq .Values.storage.type "minio"}}
        - name: ANALYZER_BINARYSTORE_TYPE
          value: "minio"
        - name: ANALYZER_BINARYSTORE_BUCKETPREFIX
          value: "{{ .Values.storage.bucket.bucketMultiPrefix }}"
        - name: MINIO_SHORT_HOST
          value: "{{ .Values.storage.endpoint | default (printf "%s-minio.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.storage.port }}"
        {{- if .Values.storage.secretName }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.accesskeyName }}"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.secretkeyName }}"
        {{- else }}
        - name: MINIO_ACCESS_KEY
          value: "{{ .Values.storage.accesskey }}"
        - name: MINIO_SECRET_KEY
          value: "{{ .Values.storage.secretkey }}"
        {{- end }}
        {{- else }}
        - name: ANALYZER_BINARYSTORE_TYPE
          value: "filesystem"
        {{- end }}
        - name: INSTANCE_TASK_TYPE
          value: "train"
        - name: UWSGI_WORKERS
          value: "{{ .Values.serviceanalyzertrain.uwsgiWorkers }}"
        - name: RP_AMQP_PASS
        {{- if .Values.msgbroker.secretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.msgbroker.secretName }}"
              key: "rabbitmq-password"
        {{- else }}
          value: "{{ .Values.msgbroker.password }}"
        {{- end }}
        - name: AMQP_URL
          value: {{ ternary "amqps" "amqp" .Values.msgbroker.ssl }}://{{ .Values.msgbroker.user }}:$(RP_AMQP_PASS)@{{ .Values.msgbroker.endpoint | default (printf "%s-rabbitmq.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.msgbroker.port }}/
        - name: AMQP_EXCHANGE_NAME
          value: "{{ .Values.msgbroker.analyzerExchangeName | default "analyzer-default" }}"
        - name: AMQP_VIRTUAL_HOST
          value: "{{ .Values.msgbroker.vhost }}"
        - name: ES_HOSTS
          value: "{{ ternary "https" "http" .Values.searchengine.ssl }}://{{ .Values.searchengine.endpoint | default (printf "opensearch-cluster-master.%s.svc.cluster.local" .Release.Namespace) }}:{{ .Values.searchengine.port }}"
        {{- if .Values.searchengine.secretName }}
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "username"
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "password"
        {{- else }}
        - name: ES_USER
          value: "{{ .Values.searchengine.user }}"
        - name: ES_PASSWORD
          value: "{{ .Values.searchengine.password }}" 
        {{- end }}
{{- if .Values.serviceanalyzertrain.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.serviceanalyzertrain.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.serviceanalyzertrain.securityContext | indent 8}}
      serviceAccountName: {{ .Values.serviceanalyzertrain.serviceAccountName | default (include "reportportal.serviceAccountName" .) }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}