apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportportal.fullname" . }}-metrics-gatherer
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-metrics-gatherer
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.metricsgatherer.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-metrics-gatherer
      annotations:
        {{- range $key, $value := .Values.metricsgatherer.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      initContainers:
      - name: migrations-waiting-init
        image: "{{ .Values.k8sWaitFor.image.repository }}:{{ .Values.k8sWaitFor.image.tag }}"
        imagePullPolicy: IfNotPresent
        args:
          - "pod-wr"
          - "-lcomponent={{ include "reportportal.fullname" . }}-api"
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
{{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
{{- end }}
      containers:
      - name: metrics-gatherer
        image: "{{ .Values.metricsgatherer.image.repository }}:{{ .Values.metricsgatherer.image.tag }}"
        imagePullPolicy: "{{ .Values.metricsgatherer.pullPolicy }}"
        ports:
        - containerPort: 5000
          name: metricsgatherer
        resources:
          requests:
            cpu: {{ .Values.metricsgatherer.resources.requests.cpu }}
            memory: {{ .Values.metricsgatherer.resources.requests.memory }}
          limits:
            cpu: {{ .Values.metricsgatherer.resources.limits.cpu }}
            memory: {{ .Values.metricsgatherer.resources.limits.memory }}
        env:
{{- if .Values.metricsgatherer.extraEnvs }}
{{ toYaml .Values.metricsgatherer.extraEnvs | indent 8 }}
{{- end }}
        - name: RP_AMQP_PASS
        {{ if .Values.msgbroker.secretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.msgbroker.secretName }}"
              key: "rabbitmq-password"
        {{ else }}
          value: "{{ .Values.msgbroker.password }}"
        {{ end }}
        - name: AMQP_URL
          value: {{ ternary "amqps" "amqp" .Values.msgbroker.ssl }}://{{ .Values.msgbroker.user }}:$(RP_AMQP_PASS)@{{ .Values.msgbroker.endpoint | default (printf "%s-rabbitmq.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.msgbroker.port }}/
        - name: AMQP_VIRTUAL_HOST
          value: "{{ .Values.msgbroker.vhost }}"
        - name: LOGGING_LEVEL
          value: "{{ .Values.metricsgatherer.loggingLevel }}"
        - name: ES_HOST
          value: "{{ ternary "https" "http" .Values.searchengine.ssl }}://{{ .Values.searchengine.endpoint | default (printf "opensearch-cluster-master.%s.svc.cluster.local" .Release.Namespace) }}:{{ .Values.searchengine.port }}"
        {{- if .Values.searchengine.secretName }}
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "username"
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "password"
        {{- else }}
        - name: ES_USER
          value: "{{ .Values.searchengine.user }}"
        - name: ES_PASSWORD
          value: "{{ .Values.searchengine.password }}" 
        {{- end }}
        - name: POSTGRES_HOST
          value: {{ .Values.database.endpoint | default (printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}
        - name: POSTGRES_PORT
          value: "{{ .Values.database.port }}"
        - name: POSTGRES_DB
          value: "{{ .Values.database.dbName }}"
        - name: POSTGRES_USER
          value: "{{ .Values.database.user }}"
        - name: POSTGRES_PASSWORD
         {{- if .Values.database.secretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.secretName }}"
              key: "postgresql-password"
        {{- else }}
          value: "{{ .Values.database.password }}"
        {{- end }}
        - name: ALLOWED_START_TIME
          value: "{{ .Values.metricsgatherer.timeManagement.starttime }}"
        - name: ALLOWED_END_TIME
          value: "{{ .Values.metricsgatherer.timeManagement.endtime }}"
        - name: MAX_DAYS_STORE
          value: "{{ .Values.metricsgatherer.maxDaysStore }}"
        - name: TZ
          value: "{{ .Values.metricsgatherer.timeManagement.timezone }}"
{{- if .Values.metricsgatherer.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.metricsgatherer.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.metricsgatherer.securityContext | indent 8}}
      serviceAccountName: {{ .Values.metricsgatherer.serviceAccountName | default (include "reportportal.serviceAccountName" .) }}
{{- with .Values.tolerations }}
      tolerations: 
{{- toYaml . | nindent 8 }}
{{- end }}