apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-metrics-gatherer
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.metricsgatherer.name | default "metrics-gatherer" }}
spec:
  ports:
  - name: {{ $.Values.metricsgatherer.service.portName | default "headless" }}
    port: 8585
    protocol: TCP
    targetPort: metricsgatherer
  selector:
    component: {{ include "reportportal.fullname" . }}-metrics-gatherer
  type: ClusterIP
  