apiVersion: v2
appVersion: "23.2"
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 23.2.1
sources:
  - https://github.com/reportportal/kubernetes
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io
dependencies:
    # If you update version, please update also postgresql.image.tag in values.yaml
  - name: postgresql
    version: 10.16.2
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.install

    # If you update version, please update also rabbitmq.image.tag in values.yaml
  - name: rabbitmq
    version: 10.3.9
    repository: https://charts.bitnami.com/bitnami  
    condition: rabbitmq.install

  - name: opensearch
    version: 2.17.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.install

  - name: minio
    version: 12.10.4
    repository: https://charts.bitnami.com/bitnami
    condition: minio.install
