apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    meta.helm.sh/release-name: reportportal
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-08-27T15:53:50Z"
  generation: 1
  labels:
    app: reportportal
    app.kubernetes.io/managed-by: Helm
    chart: reportportal-24.1.3
    heritage: Helm
    release: reportportal
  name: reportportal-migrations
  namespace: default
  resourceVersion: "13045"
  uid: 717a0c3a-ff59-426f-9c7a-280b4fb77938
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 717a0c3a-ff59-426f-9c7a-280b4fb77938
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: 717a0c3a-ff59-426f-9c7a-280b4fb77938
        batch.kubernetes.io/job-name: reportportal-migrations
        component: reportportal-migrations
        controller-uid: 717a0c3a-ff59-426f-9c7a-280b4fb77938
        job-name: reportportal-migrations
    spec:
      containers:
      - env:
        - name: POSTGRES_SSLMODE
          value: disable
        - name: POSTGRES_SERVER
          value: reportportal-postgresql.default.svc.cluster.local
        - name: POSTGRES_DB
          value: reportportal
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: rppassword
        - name: OS_HOST
          value: opensearch-cluster-master.default.svc.cluster.local
        - name: OS_PORT
          value: "9200"
        - name: OS_PROTOCOL
          value: http
        - name: OS_USER
        - name: OS_PASSWORD
        image: reportportal/migrations:5.11.1
        imagePullPolicy: Always
        name: migrations
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: reportportal
      serviceAccountName: reportportal
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2024-08-27T15:53:57Z"
  conditions:
  - lastProbeTime: "2024-08-27T15:53:57Z"
    lastTransitionTime: "2024-08-27T15:53:57Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2024-08-27T15:53:50Z"
  succeeded: 1
  terminating: 0
  uncountedTerminatedPods: {}
