apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reportportal.fullname" . }}-migrations
  labels: {{ include "labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.migrations.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-migrations
      annotations:
        {{- range $key, $value := .Values.migrations.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      restartPolicy: OnFailure
      containers:
      - env:
        - name: POSTGRES_SSLMODE
          value: "{{ .Values.database.ssl }}"
        - name: POSTGRES_SERVER
          value: {{ .Values.database.endpoint | default (printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}
        - name: POSTGRES_DB
          value: "{{ .Values.database.dbName }}"
        - name: POSTGRES_PORT
          value: "{{ .Values.database.port }}"
        - name: POSTGRES_USER
          value: "{{ .Values.database.user }}"
        - name: POSTGRES_PASSWORD
        {{ if .Values.database.secretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.secretName }}"
              key: "postgresql-password"
        {{ else }}
          value: "{{ .Values.database.password }}"
        {{ end }}
        - name: OS_HOST
          value: "{{ .Values.searchengine.endpoint | default (printf "opensearch-cluster-master.%s.svc.cluster.local" .Release.Namespace) }}"
        - name: OS_PORT
          value: "{{ .Values.searchengine.port | default "9200" }}"
        - name: OS_PROTOCOL
          value: "{{ ternary "https" "http" .Values.searchengine.ssl }}"
        - name: OS_USER
          value: "{{ .Values.searchengine.user }}"
        - name: OS_PASSWORD
          value: "{{ .Values.searchengine.password }}"
        image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
        imagePullPolicy: "{{ .Values.migrations.pullPolicy }}"
        name: migrations
        resources:
          requests:
            cpu: {{ .Values.migrations.resources.requests.cpu }}
            memory: {{ .Values.migrations.resources.requests.memory }}
          limits:
            cpu: {{ .Values.migrations.resources.limits.cpu }}
            memory: {{ .Values.migrations.resources.limits.memory }}
{{- if .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.migrations.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.migrations.securityContext | indent 8}}
      serviceAccountName: {{ .Values.migrations.serviceAccountName | default (include "reportportal.serviceAccountName" .) }}
{{- with .Values.tolerations }}
      tolerations: 
{{- toYaml . | nindent 8 }}
{{- end }}
