apiVersion: v2
appVersion: "25.1"
description: |
  ReportPortal.io is a TestOps service, that provides increased capabilities
  to speed up results analysis and reporting through the use of built-in analytic features.
name: reportportal
version: 25.7.30
sources:
  - https://github.com/reportportal/kubernetes/tree/master/reportportal
keywords:
  - reportportal
  - report portal
  - test results reporting service
  - test report dashboard
  - test automation reporting tools
  - test automation results dashboard
  - qa automation dashboard
  - qa metrics dashboard
  - automation test report
  - test execution dashboard
home: https://reportportal.io
icon: https://raw.githubusercontent.com/reportportal/branding/a4e0ac59ff51e1081d4fa754f1a06f22ea6dcfe7/logo/Logo_Symbol_Large_Ogriginal.svg
annotations:
  category: Infrastructure
  licenses: Apache-2.0
maintainers:
  - name: reportportal
    email: support@reportportal.io

# If you update dependencies version, please update also *.image.tag in values.yaml
dependencies:
  # If you update version, please update also postgresql.image.tag in values.yaml
  - name: postgresql
    version: 16.7.21
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install
    # If you update version, please update also rabbitmq.image.tag in values.yaml
  - name: rabbitmq
    version: 16.0.11
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install
  - name: opensearch
    version: 2.35.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.install
  - name: minio
    version: 17.0.16
    repository: https://charts.bitnami.com/bitnami
    condition: minio.install
