apiVersion: v1
appVersion: "5.6.1"
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 5.6.1
sources:
  - https://github.com/reportportal/kubernetes
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io
engine: gotpl
