apiVersion: v2
appVersion: "23.2"
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 5.10.0
sources:
  - https://github.com/reportportal/kubernetes
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io
dependencies:
  - name: postgresql
    version: 10.9.4
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.installdep.enable

  - name: rabbitmq
    version: 10.3.9
    repository: https://charts.bitnami.com/bitnami  
    condition: rabbitmq.installdep.enable

  - name: elasticsearch
    version: 7.10.2
    repository: https://helm.elastic.co
    condition: elasticsearch.installdep.enable

  - name: minio
    version: 7.1.9
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: storage.installdep.enable
