apiVersion: v2
appVersion: "24.1"
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 24.1.2
sources:
  - https://github.com/reportportal/kubernetes
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io
dependencies:
    # If you update version, please update also postgresql.image.tag in values.yaml
  - name: postgresql
    version: 15.3.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install

    # If you update version, please update also rabbitmq.image.tag in values.yaml
  - name: rabbitmq
    version: 14.4.4
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install

  - name: opensearch
    version: 2.20.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.install

  - name: minio
    version: 14.6.13
    repository: https://charts.bitnami.com/bitnami
    condition: minio.install
