{{- if not .Values.ingress.tls.certificate.gcpManaged }}
{{- if and .Values.ingress.tls.certificate.privateKey .Values.ingress.tls.certificate.certificate }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-gateway-tls
  labels:
    {{ include "labels" . | nindent 4 }}
data:
  tls.key: |
    {{- .Values.ingress.tls.certificate.privateKey | nindent 4 }}
  tls.crt: |
    {{- .Values.ingress.tls.certificate.certificate | nindent 4 }}
{{- end }}
{{- end }}