{{- if .Values.ingress.tls.certificate.gcpManaged }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-gcp-managed-cert
  labels:
    {{ include "labels" . | nindent 4 }}
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}