apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportportal.fullname" . }}-index
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-index
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.serviceindex.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-index
      annotations:
        {{- range $key, $value := .Values.serviceindex.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      initContainers:
      {{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceindex.serviceAccountName | default (include "reportportal.serviceAccountName" .) }}
      containers:
      - env:
        - name: K8S_MODE
          value: "true"
        # Added for Skaffold local dev environment support
        {{ if .Values.serviceindex.image }}
        image: "{{ .Values.serviceindex.image }}"
        {{ else }}
        image: "{{ .Values.serviceindex.repository }}:{{ .Values.serviceindex.tag }}"
        {{ end }}
        imagePullPolicy: "{{ .Values.serviceindex.pullPolicy }}"
        name: {{ $.Values.serviceindex.name | default "index" }}
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: {{ .Values.serviceindex.resources.requests.cpu }}
            memory: {{ .Values.serviceindex.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceindex.resources.limits.cpu }}
            memory: {{ .Values.serviceindex.resources.limits.memory }}
{{- if .Values.serviceindex.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.serviceindex.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.serviceindex.securityContext | indent 8}}
{{- with .Values.tolerations }}
      tolerations: 
{{- toYaml . | nindent 8 }}
{{- end }}
