{{- if .Values.ingress.enable }}
{{- $fullName := include "reportportal.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-gateway-ingress
  labels: {{ include "labels" . | indent 4 }}
  annotations:
  {{- if eq .Values.ingress.class "nginx" }}
    {{- range $key, $value := .Values.ingress.annotations.nginx }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- else if eq .Values.ingress.class "gke" }}
    {{- range $key, $value := .Values.ingress.annotations.gke }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- else if eq .Values.ingress.class "aws" }}
    {{- range $key, $value := .Values.ingress.annotations.aws }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- else }}
    {{- range $key, $value := .Values.ingress.annotations.custom }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if eq .Values.ingress.class "gke" }}
  {{- else if eq .Values.ingress.class "aws "}}
  {{- else }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  {{- if .Values.ingress.tls.certificates }}
  tls:
    {{ toYaml .Values.ingress.tls.certificates | nindent 4 }}
  {{- else if and .Values.ingress.tls.secret.base64EncodedPrivateKey .Values.ingress.tls.secret.base64EncodedCertificate }}
  tls:
    - secretName: {{ $fullName }}-gateway-tls
  {{- end }}
  rules:
{{ if .Values.ingress.usedomainname }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-index
            port:
              name: {{ $.Values.serviceindex.service.portName | default "headless" }}
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-ui
            port:
              name: {{ $.Values.serviceui.service.portName | default "headless" }}
      - path: /uat
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-uat
            port:
              name: {{ $.Values.uat.service.portName | default "headless" }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-api
            port:
              name: {{ $.Values.serviceapi.service.portName | default "headless" }}
  {{- end -}}
{{ else }}
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-index
            port:
              name: {{ $.Values.serviceindex.service.portName | default "headless" }}
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-ui
            port:
              name: {{ $.Values.serviceui.service.portName | default "headless" }}
      - path: /uat
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-uat
            port:
              name: {{ $.Values.uat.service.portName | default "headless" }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-api
            port:
              name: {{ $.Values.serviceapi.service.portName | default "headless" }}
{{ end }}
status:
  loadBalancer: {}
{{- end }}
