apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "reportportal.fullname" . }}-analyzer
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  {{- with .Values.serviceanalyzer.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-analyzer
  serviceName: {{ include "reportportal.fullname" . }}-analyzer
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.serviceanalyzer.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-analyzer
      annotations:
        {{- range $key, $value := .Values.serviceanalyzer.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.serviceanalyzer.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: migrations-waiting-init
        image: "{{ include "reportportal.image" (dict "Values" .Values "service" "k8sWaitFor") }}"
        imagePullPolicy: IfNotPresent
        args:
          - "pod-wr"
          - "-lcomponent={{ include "reportportal.fullname" . }}-api"
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
      {{- if .Values.serviceanalyzer.extraInitContainers }}
      {{ toYaml .Values.serviceanalyzer.extraInitContainers | nindent 6 }}
      {{- end }}
      containers:
      - name: "{{ $.Values.serviceanalyzer.name | default "analyzer" }}"
        image: "{{ include "reportportal.image" (dict "Values" .Values "service" "serviceanalyzer") }}"
        imagePullPolicy: "{{ .Values.serviceanalyzer.pullPolicy }}"
        ports:
        - containerPort: 5001
          name: analyzercore
        resources:
          {{- toYaml .Values.serviceanalyzer.resources | nindent 10 }}
        env:
        {{- if .Values.serviceanalyzer.extraEnvs }}
        {{- toYaml .Values.serviceanalyzer.extraEnvs | nindent 8 }}
        {{- end }}
        {{- $storageType := include "reportportal.storageType" . }}
        - name: DATASTORE_TYPE
          value: "{{ $storageType }}"
        {{- if or (eq $storageType "minio") (eq $storageType "s3") }}
        {{- if eq $storageType "minio" }}
        - name: DATASTORE_ENDPOINT
          value: "{{ ternary "https" "http" .Values.storage.ssl }}://{{ .Values.storage.endpoint | default (printf "%s-minio.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.storage.port }}"
        {{- else if eq $storageType "s3" }}
        - name: DATASTORE_REGION
          value: "{{ .Values.storage.region }}"
        {{- end }}
        {{- if .Values.storage.secretName }}
        - name: DATASTORE_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.accesskeyName }}"
        - name: DATASTORE_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.secretkeyName }}"
        {{- else }}
        - name: DATASTORE_ACCESSKEY
          value: "{{ .Values.storage.accesskey }}"
        - name: DATASTORE_SECRETKEY
          value: "{{ .Values.storage.secretkey }}"
        {{- end }}
        - name: DATASTORE_BUCKETPREFIX
          value: "{{ .Values.storage.bucket.bucketMultiPrefix }}"
        - name: DATASTORE_BUCKETPOSTFIX
          value: "{{ .Values.storage.bucket.bucketMultiPostfix | default "" }}"
        - name: DATASTORE_DEFAULTBUCKETNAME
          value: "{{ .Values.storage.bucket.bucketDefaultName }}/analyzer"
        {{- end }}
        - name: RP_AMQP_PASS
        {{- if .Values.msgbroker.secretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.msgbroker.secretName }}"
              key: "rabbitmq-password"
        {{- else }}
          value: "{{ .Values.msgbroker.password }}"
        {{- end }}
        - name: AMQP_URL
          value: {{ ternary "amqps" "amqp" .Values.msgbroker.ssl }}://{{ .Values.msgbroker.user }}:$(RP_AMQP_PASS)@{{ .Values.msgbroker.endpoint | default (printf "%s-rabbitmq.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.msgbroker.port }}/
        - name: AMQP_EXCHANGE_NAME
          value: "{{ .Values.msgbroker.analyzerExchangeName | default "analyzer-default" }}"
        - name: AMQP_VIRTUAL_HOST
          value: "{{ .Values.msgbroker.vhost }}"
        - name: ES_HOSTS
          value: "{{ ternary "https" "http" .Values.searchengine.ssl }}://{{ .Values.searchengine.endpoint | default (printf "opensearch-cluster-master.%s.svc.cluster.local" .Release.Namespace) }}:{{ .Values.searchengine.port }}"
        {{- if .Values.searchengine.secretName }}
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "{{ .Values.searchengine.userKeyName | default "username" }}"
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "{{ .Values.searchengine.passwordKeyName | default "password" }}"
        {{- else }}
        - name: ES_USER
          value: "{{ .Values.searchengine.user }}"
        - name: ES_PASSWORD
          value: "{{ .Values.searchengine.password }}" 
        {{- end }}
        {{- if .Values.serviceanalyzer.uwsgiWorkers }}
        - name: UWSGI_WORKERS
          value: "{{ .Values.serviceanalyzer.uwsgiWorkers }}"
        {{- end }}
        {{- if .Values.serviceanalyzer.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: {{ .Values.serviceanalyzer.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.serviceanalyzer.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.serviceanalyzer.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.serviceanalyzer.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.serviceanalyzer.readinessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.serviceanalyzer.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: {{ .Values.serviceanalyzer.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.serviceanalyzer.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.serviceanalyzer.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.serviceanalyzer.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.serviceanalyzer.livenessProbe.successThreshold }}
        {{- end }}
        volumeMounts:
          {{- if eq (include "reportportal.storageType" .) "filesystem" }}
          - name: shared-volume
            mountPath: /data/storage
          {{- end }}
          {{- if .Values.serviceanalyzer.extraVolumeMounts }}
          {{- toYaml .Values.serviceanalyzer.extraVolumeMounts | nindent 10 }}
          {{- end }}
      {{- if .Values.serviceanalyzer.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.serviceanalyzer.nodeSelector }}
        {{- $key | nindent 8 }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      securityContext:
        {{- include "reportportal.securityContext" (dict "Values" .Values "serviceContext" .Values.serviceanalyzer.securityContext) | nindent 8 }}
      serviceAccountName: {{ .Values.serviceanalyzer.serviceAccountName | default (include "reportportal.serviceAccountName" .) }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      {{- with .Values.serviceanalyzer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if or (eq (include "reportportal.storageType" .) "filesystem") .Values.serviceanalyzer.extraVolumes }}
      volumes:
        {{- if eq (include "reportportal.storageType" .) "filesystem" }}
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-shared-volume-claim
        {{- end }}
        {{- if .Values.serviceanalyzer.extraVolumes }}
        {{- toYaml .Values.serviceanalyzer.extraVolumes | nindent 8 }}
        {{- end }}
      {{- end }}