apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reportportal.fullname" . }}-migrations
  labels: {{ include "labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        component: {{ include "reportportal.fullname" . }}-migrations
    spec:
      {{- if .Values.openshift.enable }}
      serviceAccountName: {{ template "reportportal.serviceAccountName" . }}
      {{ end }}
      restartPolicy: Never
      containers:
      - env:
        - name: POSTGRES_SERVER
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.endpoint.dbName }}"
        - name: POSTGRES_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: POSTGRES_PASSWORD
        {{ if .Values.postgresql.endpoint.cloudservice }}
          value: "{{ .Values.postgresql.endpoint.password }}"
        {{ else }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        {{ end }}
        image: "{{ .Values.migrations.repository }}:{{ .Values.migrations.tag }}"
        name: migrations
        resources:
          requests:
            cpu: {{ .Values.migrations.resources.requests.cpu }}
            memory: {{ .Values.migrations.resources.requests.memory }}
          limits:
            cpu: {{ .Values.migrations.resources.limits.cpu }}
            memory: {{ .Values.migrations.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
