apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reportportal.fullname" . }}-migrations
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      labels:
        component: {{ include "reportportal.fullname" . }}-migrations
      annotations:
        {{- range $key, $value := .Values.migrations.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
      - env:
        - name: POSTGRES_SERVER
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.endpoint.dbName }}"
        - name: POSTGRES_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: POSTGRES_PASSWORD
        {{ if .Values.postgresql.endpoint.cloudservice }}
          value: "{{ .Values.postgresql.endpoint.password }}"
        {{ else }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        {{ end }}
        image: "{{ .Values.migrations.repository }}:{{ .Values.migrations.tag }}"
        name: migrations
        resources:
          requests:
            cpu: {{ .Values.migrations.resources.requests.cpu }}
            memory: {{ .Values.migrations.resources.requests.memory }}
          limits:
            cpu: {{ .Values.migrations.resources.limits.cpu }}
            memory: {{ .Values.migrations.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
