apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportportal.fullname" . }}-jobs
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-jobs
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.servicejobs.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-jobs
      annotations:
        {{- range $key, $value := .Values.servicejobs.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: migrations-waiting-init
        image: "{{ .Values.k8sWaitFor.image.repository }}:{{ .Values.k8sWaitFor.image.tag }}"
        imagePullPolicy: IfNotPresent
        args:
          - "job-wr"
          - {{ include "reportportal.fullname" . }}-migrations
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
{{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
{{- end }}
      containers:
      - name: "{{ $.Values.servicejobs.name | default "jobs" }}"
        image: "{{ .Values.servicejobs.image.repository }}:{{ .Values.servicejobs.image.tag }}"
        imagePullPolicy: "{{ .Values.servicejobs.pullPolicy }}"
        ports:
        - containerPort: 8686
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.servicejobs.resources.requests.cpu }}
            memory: {{ .Values.servicejobs.resources.requests.memory }}
          limits:
            cpu: {{ .Values.servicejobs.resources.limits.cpu }}
            memory: {{ .Values.servicejobs.resources.limits.memory }}
        env:
{{- if .Values.servicejobs.extraEnvs }}
{{ toYaml .Values.servicejobs.extraEnvs | indent 8 }}
{{- end }}
        #TODO: remove SERVER_SERVLET_CONTEXT_PATH after change base path in service-jobs
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/jobs"
        {{- if .Values.searchengine.doubleEntry }}
        - name: RP_ELASTICSEARCH_HOST
          value: "{{ ternary "https" "http" .Values.searchengine.ssl }}://{{ .Values.searchengine.endpoint | default (printf "opensearch-cluster-master.%s.svc.cluster.local" .Release.Namespace) }}:{{ .Values.searchengine.port }}"
        {{- if .Values.searchengine.secretName }}
        - name: RP_ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "username"
        - name: RP_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.searchengine.secretName }}"
              key: "password"
        {{- else }}
        - name: RP_ELASTICSEARCH_USERNAME
          value: "{{ .Values.searchengine.user }}"
        - name: RP_ELASTICSEARCH_PASSWORD
          value: "{{ .Values.searchengine.password }}"
        {{- end}}
        {{- end}}
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACHMENT_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanAttachmentCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_LOG_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanLogCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanLaunchCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanStorageCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_STORAGE_PROJECT_CRON
          value: "{{ .Values.servicejobs.coreJobs.storageProjectCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE
          value: "{{ .Values.servicejobs.chunksize }}"
        {{- if .Values.servicejobs.jvmArgs }}
        - name: JAVA_OPTS
          value: "{{ .Values.servicejobs.jvmArgs }}"
        {{- end }}
        - name: RP_AMQP_ANALYZER-VHOST
          value: "{{ .Values.msgbroker.vhost }}"
        - name: RP_AMQP_PASS
        {{- if .Values.msgbroker.secretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.msgbroker.secretName }}"
              key: "rabbitmq-password"
        {{- else }}
          value: "{{ .Values.msgbroker.password }}"
        {{- end }}
        - name: RP_AMQP_API_ADDRESS
          value: {{ ternary "https" "http" .Values.msgbroker.ssl }}://{{ .Values.msgbroker.apiuser }}:$(RP_AMQP_PASS)@{{ .Values.msgbroker.endpoint | default (printf "%s-rabbitmq.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.msgbroker.apiport }}/api
        - name: RP_AMQP_ADDRESSES
          value: '{{ ternary "amqps" "amqp" .Values.msgbroker.ssl }}://{{ .Values.msgbroker.user }}:$(RP_AMQP_PASS)@{{ .Values.msgbroker.endpoint | default (printf "%s-rabbitmq.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.msgbroker.port }}'
        - name: RP_DB_HOST
          value: {{ .Values.database.endpoint | default (printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}
        - name: RP_DB_PORT
          value: "{{ .Values.database.port }}"
        - name: RP_DB_NAME
          value: "{{ .Values.database.dbName }}"
        {{- if .Values.database.connections }}
        - name: RP_DATASOURCE_MAXIMUMPOOLSIZE
          value: "{{ .Values.database.connections }}"
        {{- end }}
        - name: RP_DB_USER
          value: "{{ .Values.database.user }}"
        - name: RP_DB_PASS
        {{- if .Values.database.secretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.secretName }}"
              key: "postgresql-password"
        {{- else }}
          value: "{{ .Values.database.password }}"
        {{- end }}
        {{- if eq .Values.storage.bucket.type "single" }}
        - name: RP_FEATURE_FLAGS
          value: "singleBucket"
        {{- end }}
        - name: DATASTORE_TYPE
          value: "{{ .Values.storage.type }}"
        {{- if eq .Values.storage.type "minio" }}
        - name: DATASTORE_ENDPOINT
          value: "{{ ternary "https" "http" .Values.storage.ssl }}://{{ .Values.storage.endpoint | default (printf "%s-minio.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}:{{ .Values.storage.port }}"
        {{- end }}
        {{- if .Values.storage.region }}
        - name: DATASTORE_REGION
          value: "{{ .Values.storage.region }}"
        {{- end }}
        {{- if .Values.storage.secretName }}
        - name: DATASTORE_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.accesskeyName }}"
        - name: DATASTORE_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.secretkeyName }}"
       {{- else }}
        - name: DATASTORE_ACCESSKEY
          value: "{{ .Values.storage.accesskey }}"
        - name: DATASTORE_SECRETKEY
          value: "{{ .Values.storage.secretkey }}"
       {{- end }}
       {{- if eq .Values.storage.bucket.type "multi" }}
        - name: DATASTORE_BUCKETPREFIX
          value: "{{ .Values.storage.bucket.bucketMultiPrefix }}"
        - name: DATASTORE_BUCKETPOSTFIX
          value: "{{ .Values.storage.bucket.bucketMultiPostfix }}"
        - name: RP_INTEGRATION_SALT_PATH
          value: "{{ .Values.storage.bucket.bucketMultiSaltName }}"
       {{- end }}
        - name: DATASTORE_DEFAULTBUCKETNAME
          value: "{{ .Values.storage.bucket.bucketDefaultName }}"
        - name: RP_PROCESSING_LOG_MAXBATCHSIZE
          value: "{{ .Values.servicejobs.logProcessing.maxBatchSize }}"
        - name: RP_PROCESSING_LOG_MAXBATCHTIMEOUT
          value: "{{ .Values.servicejobs.logProcessing.maxBatchTimeout }}"
        - name: RP_AMQP_MAXLOGCONSUMER
          value: "1"
        {{- if .Values.servicejobs.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: "/jobs/health"
            port: 8686
          initialDelaySeconds: {{ .Values.servicejobs.readinessProbe.initialDelaySeconds | default 60 }}
          periodSeconds: {{ .Values.servicejobs.readinessProbe.periodSeconds | default 40 }}
          timeoutSeconds: {{ .Values.servicejobs.readinessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.servicejobs.readinessProbe.failureThreshold | default 10 }}
        {{- end }}
        {{- if .Values.servicejobs.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: "/jobs/health"
            port: 8686
          initialDelaySeconds: {{ .Values.servicejobs.livenessProbe.initialDelaySeconds | default 60 }}
          periodSeconds: {{ .Values.servicejobs.livenessProbe.periodSeconds | default 40 }}
          timeoutSeconds: {{ .Values.servicejobs.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.servicejobs.livenessProbe.failureThreshold | default 10 }}
        {{- end }}
{{- if .Values.servicejobs.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.servicejobs.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.servicejobs.securityContext | indent 8 }}
      serviceAccountName: {{ .Values.servicejobs.serviceAccountName | default (include "reportportal.serviceAccountName" .) }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}