{{- if and .Values.uat.secret.enabled .Values.uat.secret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "reportportal.name" . }}-uat-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if .Values.uat.podLabels }}
{{ toYaml .Values.uat.podLabels | indent 4 }}
{{- end }}
data:
{{ toYaml .Values.uat.secret.data | indent 2 }}
{{- end}}

---

{{- if not .Values.uat.superadminInitPasswd.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "reportportal.name" . }}-uat-init-password
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if .Values.uat.podLabels }}
{{ toYaml .Values.uat.podLabels | indent 4 }}
{{- end }}
data:
  password: {{ .Values.uat.superadminInitPasswd.password | b64enc | quote }}
{{- end}}