{{- if .Values.postgresql.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.cluster.superuserSecret | default (printf "%s-cnpg-credentials" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.user | quote }}
  password: {{ .Values.database.password | quote }}
{{- end }}
