apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "reportportal.fullname" . }}-analyzer-train
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-analyzer-train
  serviceName: {{ include "reportportal.fullname" . }}-analyzertrain
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.serviceanalyzertrain.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-analyzer-train
      annotations:
        {{- range $key, $value := .Values.serviceanalyzertrain.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      initContainers:
      {{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      containers:
      - env:
{{- if .Values.serviceanalyzertrain.extraEnvs }}
{{ toYaml .Values.serviceanalyzertrain.extraEnvs | indent 8 }}
{{- end }}
        {{- if eq .Values.storage.type "minio"}}
        - name: ANALYZER_BINARYSTORE_TYPE
          value: "minio"
        - name: ANALYZER_BINARYSTORE_BUCKETPREFIX
          value: "{{ .Values.storage.bucket.bucketMultiPrefix }}"
        - name: MINIO_SHORT_HOST
          value: "{{ .Values.storage.endpointshort }}"
        {{- if .Values.storage.secretName }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.accesskeyName }}"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.secretkeyName }}"
        {{- else }}
        - name: MINIO_ACCESS_KEY
          value: "{{ .Values.storage.accesskey }}"
        - name: MINIO_SECRET_KEY
          value: "{{ .Values.storage.secretkey }}"
        {{- end }}
        {{- else }}
        - name: ANALYZER_BINARYSTORE_TYPE
          value: "filesystem"
        {{- end }}
        - name: INSTANCE_TASK_TYPE
          value: "train"
        - name: UWSGI_WORKERS
          value: "1"
        - name: RP_AMQP_PASS
        {{- if .Values.rabbitmq.SecretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.rabbitmq.SecretName }}"
              key: "rabbitmq-password"
        {{- else }}
          value: "{{ .Values.rabbitmq.endpoint.password }}"
        {{- end }}
        - name: AMQP_URL
          value: {{ ternary "amqps" "amqp" .Values.rabbitmq.endpoint.ssl }}://{{ .Values.rabbitmq.endpoint.user }}:$(RP_AMQP_PASS)@{{ .Values.rabbitmq.endpoint.address }}:{{ .Values.rabbitmq.endpoint.port }}/
        - name: AMQP_EXCHANGE_NAME
          value: "analyzer-default"
        - name: AMQP_VIRTUAL_HOST
          value: "{{ .Values.rabbitmq.vhost }}"
        - name: ES_HOSTS
          value: "{{ .Values.elasticsearch.endpoint }}"
        {{- if .Values.elasticsearch.secretName }}
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.elasticsearch.secretName }}"
              key: "username"
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.elasticsearch.secretName }}"
              key: "password"
        {{- else }}
        - name: ES_USER
          value: "{{ .Values.elasticsearch.user }}"
        - name: ES_PASSWORD
          value: "{{ .Values.elasticsearch.password }}" 
        {{- end }}
        image: "{{ .Values.serviceanalyzer.repository }}:{{ .Values.serviceanalyzer.tag }}"
        name: analyzer
        ports:
        - containerPort: 5001
          name: analyzertrain
        resources:
          requests:
            cpu: {{ .Values.serviceanalyzertrain.resources.requests.cpu }}
            memory: {{ .Values.serviceanalyzertrain.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceanalyzertrain.resources.limits.cpu }}
            memory: {{ .Values.serviceanalyzertrain.resources.limits.memory }}
{{- if .Values.serviceanalyzertrain.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.serviceanalyzertrain.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.serviceanalyzertrain.securityContext | indent 8}}
      serviceAccountName: {{ .Values.serviceanalyzertrain.serviceAccountName }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}