apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-analyzer-train
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    component: {{ include "reportportal.fullname" . }}-analyzer-train
  type: ClusterIP