apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportportal.fullname" . }}-api
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.serviceapi.replicaCount | default 1 }}
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-api
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.serviceapi.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-api
      annotations:
        {{- range $key, $value := .Values.serviceapi.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      initContainers:
      {{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      containers:
      - env:
{{- if .Values.serviceapi.extraEnvs }}
{{ toYaml .Values.serviceapi.extraEnvs | indent 8 }}
{{- end }}
        {{- if .Values.elasticsearch.doubleEntry.enable }}
        - name: RP_ELASTICSEARCHLOGMESSAGE_HOST
          value: "true"
        {{- end}}
        - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
          value: "info"
        - name: RP_REQUESTLOGGING
          value: "false"
        {{- if .Values.serviceapi.queues }}
        - name: RP_AMQP_QUEUES
          value: {{ .Values.serviceapi.queues.totalNumber | default "10" | quote }}
        - name: RP_AMQP_QUEUESPERPOD
          value: {{ .Values.serviceapi.queues.perPodNumber | default "10" | quote }}
        {{- else }}
        - name: RP_AMQP_QUEUES
          value: "10"
        - name: RP_AMQP_QUEUESPERPOD
          value: "10"
        {{- end }}
        {{- if .Values.serviceapi.jvmArgs }}
        - name: JAVA_OPTS
          value: "{{ .Values.serviceapi.jvmArgs }}"
        {{- end }}
        - name: RP_AMQP_ANALYZER-VHOST
          value: "{{ .Values.rabbitmq.vhost }}"
        - name: RP_AMQP_PASS
        {{- if .Values.rabbitmq.SecretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.rabbitmq.SecretName }}"
              key: "rabbitmq-password"
        {{- else }}
          value: "{{ .Values.rabbitmq.endpoint.password }}"
        {{- end }}
        - name: RP_AMQP_API_ADDRESS
          value: {{ ternary "https" "http" .Values.rabbitmq.endpoint.ssl }}://{{ .Values.rabbitmq.endpoint.apiuser }}:$(RP_AMQP_PASS)@{{ .Values.rabbitmq.endpoint.address }}:{{ .Values.rabbitmq.endpoint.apiport }}/api
        - name: RP_AMQP_ADDRESSES
          value: {{ ternary "amqps" "amqp" .Values.rabbitmq.endpoint.ssl }}://{{ .Values.rabbitmq.endpoint.user }}:$(RP_AMQP_PASS)@{{ .Values.rabbitmq.endpoint.address }}:{{ .Values.rabbitmq.endpoint.port }}
        - name: RP_DB_HOST
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: RP_DB_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: RP_DB_NAME
          value: "{{ .Values.postgresql.endpoint.dbName }}"
        {{- if .Values.postgresql.endpoint.connections }}
        - name: RP_DATASOURCE_MAXIMUMPOOLSIZE
          value: "{{ .Values.postgresql.endpoint.connections }}"
        {{- end }}
        - name: RP_DB_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: RP_DB_PASS
        {{- if .Values.postgresql.SecretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        {{- else }}
          value: "{{ .Values.postgresql.endpoint.password }}"
        {{- end }}
        {{- if eq .Values.storage.bucket.type "single" }}
        - name: RP_FEATURE_FLAGS
          value: "singleBucket"
        {{- end }}
        - name: DATASTORE_TYPE
          value: "{{ .Values.storage.type }}"
        {{- if .Values.storage.type "minio" }}
        - name: DATASTORE_ENDPOINT
          value: "{{ .Values.storage.endpoint }}"
        {{- end }}
        {{- if .Values.storage.region }}
        - name: DATASTORE_REGION
          value: "{{ .Values.storage.region }}"
        {{- end }}
        {{- if .Values.storage.secretName }}
        - name: DATASTORE_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.accesskeyName }}"
        - name: DATASTORE_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.storage.secretName }}"
              key: "{{ .Values.storage.secretkeyName }}"
       {{- else }}
        - name: DATASTORE_ACCESSKEY
          value: "{{ .Values.storage.accesskey }}"
        - name: DATASTORE_SECRETKEY
          value: "{{ .Values.storage.secretkey }}"
       {{- end }}
       {{- if eq .Values.storage.bucket.type "multi" }}
        - name: DATASTORE_BUCKETPREFIX
          value: "{{ .Values.storage.bucket.bucketMultiPrefix }}"
        - name: RP_INTEGRATION_SALT_PATH
          value: "{{ .Values.storage.bucket.bucketMultiSaltName }}"
       {{- end }}
        - name: DATASTORE_DEFAULTBUCKETNAME
          value: "{{ .Values.storage.bucket.bucketDefaultName }}"
        - name: MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED
          value: "false"
        image: "{{ .Values.serviceapi.repository }}:{{ .Values.serviceapi.tag }}"
        name: api
        ports:
        - containerPort: 8585
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.serviceapi.resources.requests.cpu }}
            memory: {{ .Values.serviceapi.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceapi.resources.limits.cpu }}
            memory: {{ .Values.serviceapi.resources.limits.memory }}
        {{- if .Values.serviceapi.readinessProbe }}
        {{- if .Values.serviceapi.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: "{{ .Values.rp.healthEndpoint }}"
            port: 8585
          initialDelaySeconds: {{ .Values.serviceapi.readinessProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.serviceapi.readinessProbe.periodSeconds | default 20 }}
          timeoutSeconds: {{ .Values.serviceapi.readinessProbe.timeoutSeconds | default 3 }}
          failureThreshold: {{ .Values.serviceapi.readinessProbe.failureThreshold | default 20 }}
        {{- end }}
        {{- end }}
        {{- if .Values.serviceapi.livenessProbe }}
        {{- if .Values.serviceapi.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: "{{ .Values.rp.healthEndpoint }}"
            port: 8585
          initialDelaySeconds: {{ .Values.serviceapi.livenessProbe.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .Values.serviceapi.livenessProbe.periodSeconds | default 20 }}
          timeoutSeconds: {{ .Values.serviceapi.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ .Values.serviceapi.livenessProbe.failureThreshold | default 5 }}
        {{- end }}
        {{- end }}
        volumeMounts:
          {{- if .Values.serviceapi.secret.enabled }}
          - mountPath: {{ .Values.serviceapi.secret.mountPath }}
            name: {{ template "reportportal.name" . }}-serviceapi-secret
            readOnly: {{ .Values.serviceapi.secret.readOnly }}
          {{- end }}
{{- if .Values.serviceapi.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.serviceapi.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{- toYaml .Values.serviceapi.securityContext | indent 8 }}
      serviceAccountName: {{ .Values.serviceapi.serviceAccountName }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      volumes:
        {{- if .Values.serviceapi.secret.enabled }}
        - name: {{ template "reportportal.name" . }}-serviceapi-secret
          secret:
            secretName: {{ template "reportportal.name" . }}-serviceapi-secret
        {{- end }}
