{{- if .Values.persistence.elasticsearch.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reportportal-elasticsearch
  labels: {{ include "labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.elasticsearch.spec.capacity.storage }}
{{- end -}}