apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels: {{ include "labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    component: reportportal-elasticsearch
  type: ClusterIP
