{{- if or (not (hasKey .Values.migrations "enabled")) .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reportportal.fullname" . }}-migrations
  labels: {{ include "labels" . | indent 4 }}
{{- if .Values.migrations.metadataAnnotations.enabled }}
  annotations:
    {{- range $key, $value := .Values.migrations.metadataAnnotations.hooks }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.migrations.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-migrations
      annotations:
        {{- range $key, $value := .Values.migrations.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
      - env:
        - name: POSTGRES_SSLMODE
          value: "{{ .Values.postgresql.endpoint.ssl }}"
        - name: POSTGRES_SERVER
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.postgresqlDatabase }}"
        - name: POSTGRES_PORT
          value: "{{ .Values.postgresql.servicePort }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.postgresqlUsername }}"
        - name: POSTGRES_PASSWORD
        {{ if .Values.postgresql.SecretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        {{ else }}
          value: "{{ .Values.postgresql.postgresqlPassword }}"
        {{ end }}
        image: "{{ .Values.migrations.repository }}:{{ .Values.migrations.tag }}"
        name: migrations
        resources:
          requests:
            cpu: {{ .Values.migrations.resources.requests.cpu }}
            memory: {{ .Values.migrations.resources.requests.memory }}
          limits:
            cpu: {{ .Values.migrations.resources.limits.cpu }}
            memory: {{ .Values.migrations.resources.limits.memory }}
{{- if .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.migrations.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.migrations.securityContext | indent 8}}
      serviceAccountName: {{ .Values.migrations.serviceAccountName }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations: 
{{- toYaml . | nindent 8 }}
{{- end }}
