{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reportportal.fullname" . }}-network-policy
  labels: {{ include "labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ $.Chart.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8585
        - protocol: TCP
          port: 9999
        - protocol: TCP
          port: 8686
        - protocol: TCP
          port: 5001
    # Allow internal communication between ReportPortal services
    - from:
        - podSelector:
            matchLabels:
              app: {{ $.Chart.Name }}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8585
        - protocol: TCP
          port: 9999
        - protocol: TCP
          port: 8686
        - protocol: TCP
          port: 5001
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    {{- if .Values.networkPolicy.allowExternalServices }}
    # Allow access to external services (when enabled)
    - to: []
      ports:
        - protocol: TCP
          port: 5432  # External PostgreSQL
        - protocol: TCP
          port: 5672  # External RabbitMQ AMQP
        - protocol: TCP
          port: 15672 # External RabbitMQ Management
        - protocol: TCP
          port: 9200  # External OpenSearch
        - protocol: TCP
          port: 9000  # External MinIO
        - protocol: TCP
          port: 9001  # External MinIO Console
    {{- else }}
    # Allow access to internal database
    - to:
        - podSelector:
            matchLabels:
              app: postgresql
      ports:
        - protocol: TCP
          port: 5432
    # Allow access to internal message broker
    - to:
        - podSelector:
            matchLabels:
              app: rabbitmq
      ports:
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 15672
    # Allow access to internal search engine
    - to:
        - podSelector:
            matchLabels:
              app: opensearch
      ports:
        - protocol: TCP
          port: 9200
    # Allow access to internal storage
    - to:
        - podSelector:
            matchLabels:
              app: minio
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9001
    {{- end }}
    {{- if .Values.networkPolicy.additionalEgressRules }}
    {{- range .Values.networkPolicy.additionalEgressRules }}
    # Additional egress rule: {{ .name | default "custom" }}
    - to:
      {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector | nindent 14 }}
      {{- end }}
      {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector | nindent 14 }}
      {{- end }}
      {{- if .ipBlock }}
        - ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
      {{- end }}
      {{- if not (or .namespaceSelector .podSelector .ipBlock) }}
        - {}
      {{- end }}
      ports:
      {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }} 