{{- if and .Values.podDisruptionBudget.enabled (gt (.Values.serviceui.replicaCount | default 1) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "reportportal.fullname" . }}-ui-pdb
  labels: {{ include "labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-ui
{{- end }}

{{- if and .Values.podDisruptionBudget.enabled (gt (.Values.serviceapi.replicaCount | default 1) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "reportportal.fullname" . }}-api-pdb
  labels: {{ include "labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-api
{{- end }} 