{{- if and (.Values.persistence.registry.enabled) (not .Values.persistence.registry.useExisting) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reportportal-registry
  labels: {{ include "labels" . | indent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.registry.spec.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.registry.spec.capacity.storage }}
{{- if .Values.persistence.registry.spec.storageClass }}
{{- if (eq "-" .Values.persistence.registry.spec.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.registry.spec.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
