{{- if .Values.rbac.create }}

apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "reportportal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- if .Values.rbac.serviceAccount.annotations }}
    annotations:
      {{- range $key, $value := .Values.rbac.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ include "reportportal.fullname" . }}-service-reader
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups:
        - ""
      resources: ["pods","services"]
      verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ include "reportportal.fullname" . }}-user-binding
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "reportportal.fullname" . }}-service-reader
subjects:
    - kind: ServiceAccount
      name: {{ template "reportportal.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{- end -}}
