apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-ui
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.serviceui.name | default "ui" }}
    infoEndpoint: {{ $.Values.rp.infoEndpoint | default "/info"}}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: {{ include "reportportal.fullname" . }}-ui
  type: ClusterIP
