{{- if not .Values.serviceapi.auth.superadminInitPasswd.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "reportportal.name" . }}-api-init-password
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if .Values.serviceapi.podLabels }}
{{ toYaml .Values.serviceapi.podLabels | indent 4 }}
{{- end }}
data:
  password: {{ .Values.serviceapi.auth.superadminInitPasswd.password | b64enc | quote }}
{{- end}}
