apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-api
  labels: {{ include "labels" . | indent 4 }}
    {{- with .Values.serviceapi.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    service: {{ $.Values.serviceapi.name | default "api" }}
    infoEndpoint: "{{ .Values.ingress.path }}/api/info"
    healthEndpoint: "{{ .Values.ingress.path }}/api/health"
    {{- if eq .Values.ingress.class "alb" }}
    # ALB health check annotations
    alb.ingress.kubernetes.io/healthcheck-path: "{{ .Values.ingress.path }}/api/health"
    alb.ingress.kubernetes.io/healthcheck-port: "8585"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    {{- end }}
    {{- with .Values.serviceapi.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.serviceapi.service.type | default "ClusterIP" }}
  ports:
  - name: {{ $.Values.serviceapi.service.portName | default "headless" }}
    port: 8585
    protocol: TCP
    targetPort: 8585
{{- if and (or (eq .Values.serviceapi.service.type "NodePort") (eq .Values.serviceapi.service.type "LoadBalancer")) (not (empty .Values.serviceapi.service.nodePort)) }}
    nodePort: {{ .Values.serviceapi.service.nodePort }}
{{- end }}
{{- if .Values.serviceapi.service.extraPorts }}
  {{ toYaml .Values.serviceapi.service.extraPorts | indent 2 }}
{{- end }}
  selector:
    component: {{ include "reportportal.fullname" . }}-api