apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-api
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.serviceapi.name | default "api" }}
    infoEndpoint: "/api/info"
    healthEndpoint: "/api/health"
spec:
  type: {{ $.Values.serviceapi.service.type | default "ClusterIP" }}
  ports:
  - name: {{ $.Values.serviceapi.service.portName | default "headless" }}
    port: 8585
    protocol: TCP
    targetPort: 8585
{{- if and (or (eq .Values.serviceapi.service.type "NodePort") (eq .Values.serviceapi.service.type "LoadBalancer")) (not (empty .Values.serviceapi.service.nodePort)) }}
    nodePort: {{ .Values.serviceapi.service.nodePort }}
{{- end }}
{{- if .Values.serviceapi.service.extraPorts }}
  {{ toYaml .Values.serviceapi.service.extraPorts | indent 2 }}
{{- end }}
  selector:
    component: {{ include "reportportal.fullname" . }}-api