{{- if and .Values.serviceapi.secret.enabled .Values.serviceapi.secret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "reportportal.name" . }}-serviceapi-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if .Values.serviceapi.podLabels }}
{{ toYaml .Values.serviceapi.podLabels | indent 4 }}
{{- end }}
data:
{{ toYaml .Values.serviceapi.secret.data | indent 2 }}
{{- end}}
