{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ .Release.Name }}-user-binding
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Release.Name }}-service-reader
subjects:
    - kind: ServiceAccount
      name: {{ template "reportportal.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}