apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels: {{ include "labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-aggregator
  type: ClusterIP