name: Lint Chart

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --charts ./reportportal --target-branch ${{ github.event.repository.default_branch }}

  dry-run-test:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Build dependencies
        run: |
          helm dependency build ./reportportal

      - name: Dry run installation
        run: |
          helm install reportportal-test . --dry-run \
            --set uat.superadminInitPasswd.password="testpassword123" \
            --set postgresql.install=true \
            --set rabbitmq.install=true \
            --set opensearch.install=true \
            --set minio.install=true \
            ./reportportal