name: Lint Chart

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v4.1.0

      - name: Install helm-values-schema-json plugin
        run: helm plugin install https://github.com/losisin/helm-values-schema-json.git --verify=false

      - name: Verify values schema is up to date
        run: |
          cd reportportal
          helm schema --values values.yaml --draft 7 --use-helm-docs --output values.schema.generated.json
          diff -u values.schema.json values.schema.generated.json

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (lint)
        run: ct lint --charts ./reportportal --target-branch ${{ github.event.repository.default_branch }}

  dry-run-test:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v4.1.0

      - name: Build dependencies
        run: |
          helm dependency build ./reportportal

      - name: Template validation
        run: |
          helm template reportportal-test ./reportportal \
            --set uat.superadminInitPasswd.password="testpassword123" \
            --set postgresql.install=true \
            --set rabbitmq.install=true \
            --set opensearch.install=true \
            --set seaweedfs.install=false \
            --set minio.install=true > /dev/null