apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-shared-volume
  annotations: 
    {{ .Values.storage.filesystem.volume.annotations | toYaml | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.filesystem.volume.capacity }}
  volumeMode: Filesystem
  accessModes:
    {{- range .Values.storage.filesystem.volume.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.storage.filesystem.volume.reclaimPolicy }}
  storageClassName: {{ .Values.storage.filesystem.volume.storageClassName }}
  hostPath:
    path: "/data/{{ .Release.Name }}-shared-volume"
