apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-shared-volume
  annotations: {}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
  hostPath:
    path: "/data/{{ .Release.Name }}-shared-volume"
