apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-volume-claim
  annotations: 
    {{ .Values.storage.filesystem.volume.annotations | toYaml | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.storage.filesystem.volume.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.filesystem.volume.capacity }}
  storageClassName: {{ .Values.storage.filesystem.volume.storageClassName }}
