{{- if eq .Values.storage.type "filesystem" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-volume-claim
  {{- with .Values.storage.volume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.storage.volume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.volume.capacity }}
  storageClassName: {{ .Values.storage.volume.storageClassName }}
{{- if (ne .Values.storage.volume.volumeConfig.type "") }}
  {{- /* We have provisioned a PV for this PVC */}}
  volumeName: {{ .Release.Name }}-shared-volume
{{- end }}
{{- end }}