{{- if eq .Values.storage.type "filesystem" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-volume-claim
  annotations: 
    {{ .Values.storage.volume.annotations | toYaml | nindent 4 }}
spec:
  accessModes: 
    - {{ .Values.storage.volume.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.storage.volume.capacity }}
  storageClassName: {{ .Values.storage.volume.storageClassName }}
{{- end }}